const SET_SHOWSIDENAV = 'SET_SHOWSIDENAV';
const SET_USER = 'SET_USER';
const LOGOUT_USER = 'LOGOUT_USER';
const SET_ERROR = 'SET_ERROR';
const ADD_TEST = 'ADD_TEST';
const UPDATE_TEST = 'UPDATE_TEST';
const ADD_APPLICATION = 'ADD_APPLICATION';
const UPDATE_APPLICATION = 'UPDATE_APPLICATION';
const SET_TESTS = 'SET_TESTS';
const DELETE_TEST = 'DELETE_TEST';
const SET_APPLICATIONS = 'SET_APPLICATIONS';
const DELETE_APPLICATION = 'DELETE_APPLICAITON';

const actionTypes = {
  SET_SHOWSIDENAV,
  SET_USER,
  LOGOUT_USER,
  SET_ERROR,
  ADD_TEST,
  ADD_APPLICATION,
  UPDATE_APPLICATION,
  SET_TESTS,
  SET_APPLICATIONS,
  DELETE_APPLICATION,
  UPDATE_TEST,
  DELETE_TEST,
};

export default actionTypes;
